version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - C:\Users\HP\Desktop\Stage_PFA_2026\kpi-monitoring-platform\data:/app/data
    env_file:
      - .env 
    environment:
      - PYTHONPATH=/app
    networks:
      - kpi-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - kpi-network

networks:
  kpi-network:
    driver: bridge