# Étape 1 : Build
FROM node:24-slim AS builder
WORKDIR /app
COPY kpi-frontend/package.json kpi-frontend/package-lock.json ./
RUN npm install
COPY kpi-frontend/ .
RUN npm run build

# Étape 2 : Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]