name: CI/CD KPI Monitoring Platform

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Créer le fichier .env
        run: |
          cat > .env << EOF
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
          OPERATEUR_DEFAULT_PASSWORD=${{ secrets.OPERATEUR_DEFAULT_PASSWORD }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          EOF

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ── BACKEND ────────────────────────────────────────────
      - name: Build & Push image backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: harrouchasiham/kpi-backend:latest

      # ── FRONTEND ───────────────────────────────────────────
      - name: Build & Push image frontend
        uses: docker/build-push-action@v5
        with:
           context: .
           file: ./Dockerfile.frontend
           push: true
           tags: harrouchasiham/kpi-frontend:latest
           build-args: |
              VITE_WS_URL=wss://kpi-backend-latest.onrender.com
              VITE_API_URL=https://kpi-backend-latest.onrender.com

      # ── TRIGGER RENDER ─────────────────────────────────────
      - name: Trigger Render Deploy Backend
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK}}"
          echo "✅ Backend deploy déclenché !"

      - name: Trigger Render Deploy Frontend
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"
          echo "✅ Frontend deploy déclenché !"