name: CI/CD KPI Monitoring Platform

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Builder les images Docker
        run: docker compose build

      - name: Tester le backend
        run: |
          docker compose up -d
          sleep 10
          curl -f http://localhost:8000/ || exit 1
          docker compose down

  deploy:
    runs-on: self-hosted
    needs: build-and-test
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Redémarrer Docker automatiquement
        run: |
           docker stop $(docker ps -q) 2>$null || true
           docker compose down
           docker compose up -d --build